CREATE TABLE IF NOT EXISTS planet_has_section (
	game_id INT(10) UNSIGNED NOT NULL,
	sector_id INT(10) UNSIGNED NOT NULL,
	planet_section ENUM('CONSTRUCTION', 'DEFENSE', 'FINANCE', 'STOCKPILE', 'OWNERSHIP') NOT NULL
);